INSERT INTO cargo_types (code, name_ru, name_uz, name_en, name_tr, name_zh) VALUES
  ('MOROZHENOE', 'Мороженое', 'Мороженое', 'MOROZHENOE', 'MOROZHENOE', 'MOROZHENOE'),
  ('FARSH', 'Фарш', 'Фарш', 'FARSH', 'FARSH', 'FARSH'),
  ('PESOK', 'Песок', 'Песок', 'PESOK', 'PESOK', 'PESOK'),
  ('PISCHEVAYA_DOBAVKA', 'Пищевая добавка', 'Пищевая добавка', 'PISCHEVAYA DOBAVKA', 'PISCHEVAYA DOBAVKA', 'PISCHEVAYA DOBAVKA'),
  ('DVERI', 'Двери', 'Двери', 'DVERI', 'DVERI', 'DVERI'),
  ('OTRUBI', 'Отруби', 'Отруби', 'OTRUBI', 'OTRUBI', 'OTRUBI'),
  ('STEKLYANNYE_BUTYLKI', 'Стеклянные бутылки', 'Стеклянные бутылки', 'STEKLYANNYE BUTYLKI', 'STEKLYANNYE BUTYLKI', 'STEKLYANNYE BUTYLKI'),
  ('ALKOGOLNYE_NAPITKI', 'Алкогольные напитки', 'Алкогольные напитки', 'ALKOGOLNYE NAPITKI', 'ALKOGOLNYE NAPITKI', 'ALKOGOLNYE NAPITKI'),
  ('DVIGATEL', 'Двигатель', 'Двигатель', 'DVIGATEL', 'DVIGATEL', 'DVIGATEL'),
  ('STELLAZH', 'Стилаж', 'Стилаж', 'STELLAZH', 'STELLAZH', 'STELLAZH'),
  ('TORTILYA', 'Тортилья', 'Тортилья', 'TORTILYA', 'TORTILYA', 'TORTILYA'),
  ('KUKURUZA', 'Кукуруза', 'Кукуруза', 'KUKURUZA', 'KUKURUZA', 'KUKURUZA'),
  ('BUMAZHNAYA_SALFETKA', 'Бумажная салфетка', 'Бумажная салфетка', 'BUMAZHNAYA SALFETKA', 'BUMAZHNAYA SALFETKA', 'BUMAZHNAYA SALFETKA'),
  ('MINERALNYE_UDOBRENIYA', 'Минеральные удобрения', 'Минеральные удобрения', 'MINERALNYE UDOBRENIYA', 'MINERALNYE UDOBRENIYA', 'MINERALNYE UDOBRENIYA'),
  ('MINERALNAYA_VATA', 'Минеральная вата', 'Минеральная вата', 'MINERALNAYA VATA', 'MINERALNAYA VATA', 'MINERALNAYA VATA'),
  ('PREDMETY_DOMASHNEGO_OBIHODA', 'Предметы домашнего обихода', 'Предметы домашнего обихода', 'PREDMETY DOMASHNEGO OBIHODA', 'PREDMETY DOMASHNEGO OBIHODA', 'PREDMETY DOMASHNEGO OBIHODA'),
  ('CHIZKEYK', 'Чизкейк', 'Чизкейк', 'CHIZKEYK', 'CHIZKEYK', 'CHIZKEYK'),
  ('GRIBY', 'Грибы', 'Грибы', 'GRIBY', 'GRIBY', 'GRIBY'),
  ('MAYONEZ', 'Майонез', 'Майонез', 'MAYONEZ', 'MAYONEZ', 'MAYONEZ'),
  ('SIR', 'Сыр', 'Сыр', 'SIR', 'SIR', 'SIR'),
  ('NETKANYI_MATERIAL', 'Нетканый материал', 'Нетканый материал', 'NETKANYI MATERIAL', 'NETKANYI MATERIAL', 'NETKANYI MATERIAL'),
  ('GRANIT', 'Гранит', 'Гранит', 'GRANIT', 'GRANIT', 'GRANIT'),
  ('POROSHOK', 'Порошок', 'Порошок', 'POROSHOK', 'POROSHOK', 'POROSHOK'),
  ('PISCHEVYE_KONCENTRATY', 'Концентраты пищевые', 'Концентраты пищевые', 'PISCHEVYE KONTsENTRATY', 'PISCHEVYE KONTsENTRATY', 'PISCHEVYE KONTsENTRATY'),
  ('POLIETILEN_V_RULONAH', 'Полиэтилен в рулонах', 'Полиэтилен в рулонах', 'POLIETILEN V RULONAH', 'POLIETILEN V RULONAH', 'POLIETILEN V RULONAH'),
  ('RULONNAYA_PLENKA', 'Рулонная плёнка', 'Рулонная плёнка', 'RULONNAYA PLENKA', 'RULONNAYA PLENKA', 'RULONNAYA PLENKA'),
  ('CHISTYASHCHIE_SREDSTVA', 'Чистящие средства', 'Чистящие средства', 'CHISTYASHCHIE SREDSTVA', 'CHISTYASHCHIE SREDSTVA', 'CHISTYASHCHIE SREDSTVA'),
  ('SUSHENYE_RASTENIYA', 'Сушеные растения', 'Сушеные растения', 'SUSHENYE RASTENIYA', 'SUSHENYE RASTENIYA', 'SUSHENYE RASTENIYA'),
  ('PSHENITSA', 'Пшеница', 'Пшеница', 'PSHENITSA', 'PSHENITSA', 'PSHENITSA'),
  ('SERA', 'Сера', 'Сера', 'SERA', 'SERA', 'SERA'),
  ('MOTORNOE_MASLO', 'Моторное масло', 'Моторное масло', 'MOTORNOE MASLO', 'MOTORNOE MASLO', 'MOTORNOE MASLO'),
  ('STEKLOVATA', 'Стекловата', 'Стекловата', 'STEKLOVATA', 'STEKLOVATA', 'STEKLOVATA'),
  ('SULFAT_KALIYA', 'Сульфат калия', 'Сульфат калия', 'SULFAT KALIYA', 'SULFAT KALIYA', 'SULFAT KALIYA'),
  ('NAPITKI', 'Напитки', 'Напитки', 'NAPITKI', 'NAPITKI', 'NAPITKI'),
  ('KARTOFEL', 'Картофель', 'Картофель', 'KARTOFEL', 'KARTOFEL', 'KARTOFEL'),
  ('HIMICHESKAYA_ZHIDKOST', 'Химическая жидкость', 'Химическая жидкость', 'HIMICHESKAYA ZHIDKOST', 'HIMICHESKAYA ZHIDKOST', 'HIMICHESKAYA ZHIDKOST'),
  ('KABEL', 'Кабель', 'Кабель', 'KABEL', 'KABEL', 'KABEL'),
  ('MOLOCHNYE_PRODUKTY', 'Молочные продукты', 'Молочные продукты', 'MOLOCHNYE PRODUKTY', 'MOLOCHNYE PRODUKTY', 'MOLOCHNYE PRODUKTY'),
  ('METALLICHESKIE_KRUGI', 'Металлические круги', 'Металлические круги', 'METALLICHESKIE KRUGI', 'METALLICHESKIE KRUGI', 'METALLICHESKIE KRUGI'),
  ('UPAKOVOCHNYI_MATERIAL', 'Упаковочный материал', 'Упаковочный материал', 'UPAKOVOCHNYI MATERIAL', 'UPAKOVOCHNYI MATERIAL', 'UPAKOVOCHNYI MATERIAL'),
  ('KRYSHKI', 'Крышки', 'Крышки', 'KRYSHKI', 'KRYSHKI', 'KRYSHKI'),
  ('BONKA', 'Бонка', 'Бонка', 'BONKA', 'BONKA', 'BONKA'),
  ('TEKSTIL', 'Текстиль', 'Текстиль', 'TEKSTIL', 'TEKSTIL', 'TEKSTIL'),
  ('KORM_DLYA_ZHIVOTNYH', 'Корм для животных', 'Корм для животных', 'KORM DLYA ZHIVOTNYH', 'KORM DLYA ZHIVOTNYH', 'KORM DLYA ZHIVOTNYH'),
  ('SPICHKA', 'Cпичка', 'Cпичка', 'SPICHKA', 'SPICHKA', 'SPICHKA'),
  ('DSP', 'ДСП', 'ДСП', 'DSP', 'DSP', 'DSP'),
  ('BEREZOVYI_BALANS', 'Берёзовый баланс', 'Берёзовый баланс', 'BEREZOVYI BALANS', 'BEREZOVYI BALANS', 'BEREZOVYI BALANS'),
  ('KORMOVAYA_DOBAVKA', 'Кормовая добавка', 'Кормовая добавка', 'KORMOVAYA DOBAVKA', 'KORMOVAYA DOBAVKA', 'KORMOVAYA DOBAVKA'),
  ('HIMICHESKII_POROSHOK', 'Химический порошок', 'Химический порошок', 'HIMICHESKII POROSHOK', 'HIMICHESKII POROSHOK', 'HIMICHESKII POROSHOK'),
  ('PLENKA', 'Плёнка', 'Плёнка', 'PLENKA', 'PLENKA', 'PLENKA'),
  ('RYBA', 'Рыба', 'Рыба', 'RYBA', 'RYBA', 'RYBA'),
  ('BITUM', 'Битум', 'Битум', 'BITUM', 'BITUM', 'BITUM'),
  ('FANERA', 'Фанера', 'Фанера', 'FANERA', 'FANERA', 'FANERA'),
  ('KAPER', 'Капер', 'Капер', 'KAPER', 'KAPER', 'KAPER'),
  ('GRANULA', 'Гранула', 'Гранула', 'GRANULA', 'GRANULA', 'GRANULA'),
  ('STOLESHNITSA', 'Столешница', 'Столешница', 'STOLESHNITSA', 'STOLESHNITSA', 'STOLESHNITSA'),
  ('NITKI', 'Нитки', 'Нитки', 'NITKI', 'NITKI', 'NITKI'),
  ('OTSINKOVANNYI_RULON', 'Оцинкованный рулон', 'Оцинкованный рулон', 'OTSINKOVANNYI RULON', 'OTSINKOVANNYI RULON', 'OTSINKOVANNYI RULON'),
  ('SUHOFIL', 'Сухофрукты', 'Сухофрукты', 'SUHOFIL', 'SUHOFIL', 'SUHOFIL'),
  ('KONTSENTRAT', 'Концентрат', 'Концентрат', 'KONTSENTRAT', 'KONTSENTRAT', 'KONTSENTRAT'),
  ('TOMATNAYA_PASTA', 'Томатная паста', 'Томатная паста', 'TOMATNAYA PASTA', 'TOMATNAYA PASTA', 'TOMATNAYA PASTA'),
  ('RULON', 'Рулон', 'Рулон', 'RULON', 'RULON', 'RULON'),
  ('TSEMENT', 'Цемент', 'Цемент', 'TSEMENT', 'TSEMENT', 'TSEMENT'),
  ('KURINYE_LAPKI', 'Куринные лапки', 'Куринные лапки', 'KURINYE LAPKI', 'KURINYE LAPKI', 'KURINYE LAPKI'),
  ('YAITSO', 'Яйцо', 'Яйцо', 'YAITSO', 'YAITSO', 'YAITSO'),
  ('BYTOVAYA_TEHNIKA', 'Бытовая техника', 'Бытовая техника', 'BYTOVAYA TEHNIKA', 'BYTOVAYA TEHNIKA', 'BYTOVAYA TEHNIKA'),
  ('OTSELINDROVKA', 'Оцелиндровка', 'Оцелиндровка', 'OTSELINDROVKA', 'OTSELINDROVKA', 'OTSELINDROVKA')
ON CONFLICT (code) DO NOTHING;

