package reference

// countryNameToAlpha2 maps country names (as in tidwall/cities) to ISO 3166-1 alpha-2.
var countryNameToAlpha2 = map[string]string{
	"Afghanistan": "AF", "Albania": "AL", "Algeria": "DZ", "Andorra": "AD", "Angola": "AO",
	"Argentina": "AR", "Armenia": "AM", "Australia": "AU", "Austria": "AT", "Azerbaijan": "AZ",
	"Bahrain": "BH", "Bangladesh": "BD", "Barbados": "BB", "Belarus": "BY", "Belgium": "BE",
	"Belize": "BZ", "Benin": "BJ", "Bhutan": "BT", "Bolivia": "BO", "Bosnia and Herzegovina": "BA",
	"Brazil": "BR", "Brunei": "BN", "Bulgaria": "BG", "Cambodia": "KH", "Cameroon": "CM",
	"Canada": "CA", "Cape Verde": "CV", "Central African Republic": "CF", "Chad": "TD",
	"Chile": "CL", "China": "CN", "Colombia": "CO", "Comoros": "KM", "Costa Rica": "CR",
	"Croatia": "HR", "Cuba": "CU", "Cyprus": "CY", "Czech Republic": "CZ", "Denmark": "DK",
	"Djibouti": "DJ", "Ecuador": "EC", "El Salvador": "SV", "Equatorial Guinea": "GQ",
	"Eritrea": "ER", "Estonia": "EE", "Ethiopia": "ET", "Fiji": "FJ", "Finland": "FI",
	"France": "FR", "Gabon": "GA", "Gambia, The": "GM", "Georgia": "GE", "Germany": "DE",
	"Ghana": "GH", "Greece": "GR", "Grenada": "GD", "Guatemala": "GT", "Guyana": "GY",
	"Haiti": "HT", "Honduras": "HN", "Hungary": "HU", "Iceland": "IS", "India": "IN",
	"Indonesia": "ID", "Iran": "IR", "Iraq": "IQ", "Ireland": "IE", "Israel": "IL",
	"Italy": "IT", "Jamaica": "JM", "Japan": "JP", "Jordan": "JO", "Kazakhstan": "KZ",
	"Kenya": "KE", "Kiribati": "KI", "Korea, North": "KP", "Korea, South": "KR", "Kuwait": "KW",
	"Kyrgyzstan": "KG", "Latvia": "LV", "Lebanon": "LB", "Liberia": "LR", "Libya": "LY",
	"Liechtenstein": "LI", "Lithuania": "LT", "Luxembourg": "LU", "Macedonia": "MK",
	"Madagascar": "MG", "Malawi": "MW", "Malaysia": "MY", "Maldives": "MV", "Malta": "MT",
	"Marshall Islands": "MH", "Mauritania": "MR", "Mauritius": "MU", "Mexico": "MX",
	"Micronesia": "FM", "Moldova": "MD", "Mongolia": "MN", "Morocco": "MA", "Mozambique": "MZ",
	"Myanmar": "MM", "Nepa": "NP", "Nepal": "NP", "Netherlands": "NL", "New Zealand": "NZ",
	"Nicaragua": "NI", "Niger": "NE", "Nigeria": "NG", "Norway": "NO", "Oman": "OM",
	"Pakistan": "PK", "Palau": "PW", "Panama": "PA", "Papua New Guinea": "PG", "Paraguay": "PY",
	"Peru": "PE", "Philippines": "PH", "Poland": "PL", "Portugal": "PT", "Qatar": "QA",
	"Romania": "RO", "Russia": "RU", "Saint Kitts and Nevis": "KN", "Samoa": "WS",
	"Sao Tome and Principe": "ST", "Senegal": "SN", "Seychelles": "SC", "Slovenia": "SI",
	"Solomon Islands": "SB", "Somalia": "SO", "South Africa": "ZA", "Spain": "ES",
	"Sri Lanka": "LK", "Sudan": "SD", "Suriname": "SR", "Swaziland": "SZ", "Sweden": "SE",
	"Switzerland": "CH", "Syria": "SY", "Tajikistan": "TJ", "Tanzania": "TZ", "Thailand": "TH",
	"Togo": "TG", "Tonga": "TO", "Tunisia": "TN", "Turkey": "TR", "Turkmenistan": "TM",
	"Tuvalu": "TV", "Uganda": "UG", "Ukraine": "UA", "United Arab Emirates": "AE",
	"United Kingdom": "GB", "United States": "US", "Uruguay": "UY", "Uzbekistan": "UZ",
	"Venezuela": "VE", "Vietnam": "VN", "Yemen": "YE", "Zambia": "ZM", "Zimbabwe": "ZW",
}
